
DROP TABLE IF EXISTS `PRODUCER`;
CREATE TABLE IF NOT EXISTS `PRODUCER` (
  `PRODUCERNAME` varchar(50) NULL,
  `DESCRIPTION` varchar(50) NULL,
PRIMARY KEY (`PRODUCERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
