
START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `casefile`;

CREATE TABLE IF NOT EXISTS `casefile` (
  `IDCASEFILE`      bigint(20)  NULL AUTO_INCREMENT,
  `IDBATCH`         bigint(20)  NULL,
  `BATCHNAME`       varchar(50) NULL,
  `LIMSBATCHID` bigint(20) NULL,
  `LIMSFOLDERNO`       varchar(50) NULL,
  `IDSTATUS` tinyint(1) NULL,
  `STATUSLABEL`       varchar(50) NULL,
  `IDAPPROBATIONSTATUS` tinyint(1) NULL,
  `APPROBATIONSTATUSLABEL`       varchar(50) NULL,
  `DESCRIPTION`     varchar(50) NULL,
  
PRIMARY KEY (`IDCASEFILE`) COMMENT 'PK_CASEFILE_IDCASEFILE'
,KEY `KEY_CASEFILE_IDBATCH` (`IDBATCH`) COMMENT 'KEY_CASEFILE_IDBATCH'
,KEY `KEY_CASEFILE_LIMSFOLDERNO` (`LIMSFOLDERNO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;


START TRANSACTION;
ALTER TABLE `casefile`
ADD CONSTRAINT `FK_CASEFILE__IDBATCH` FOREIGN KEY (`IDBATCH`) REFERENCES `batch` (`IDBATCH`);
COMMIT;

SET foreign_key_checks = 1;