START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `stage`;
CREATE TABLE IF NOT EXISTS stage (
    IDSTAGE         VARCHAR(50) NULL ,
    DESCRIPTION     VARCHAR(50) NULL,
    STAGENAME    VARCHAR(50) NULL ,
PRIMARY KEY (IDSTAGE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;
SET foreign_key_checks = 1;