SET foreign_key_checks = 0;
START TRANSACTION;
DROP TABLE IF EXISTS `heritagebytransformation`;
CREATE TABLE IF NOT EXISTS `heritagebytransformation` (
  `IDTRANSFORMATIONDEP`             bigint(20) NULL,
  `IDTRANSFORMATIONARR`             bigint(20) NULL ,
 `IDMODELANALYSIS` bigint(20) NULL,
  `DESCRIPTION`                     varchar(50) NULL,
PRIMARY KEY (
    `IDTRANSFORMATIONDEP`,
    `IDTRANSFORMATIONARR`,
    `IDMODELANALYSIS`
) COMMENT 'PK_HERITAGEBYTRANSFORMATION'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;

START TRANSACTION;
ALTER TABLE `heritagebytransformation` 
    ADD CONSTRAINT `FK_HERITAGEBYTRANSFORMATIONDEP_TRANSFORMATIONDEP` 
    FOREIGN KEY (`IDTRANSFORMATIONDEP`) 
    REFERENCES `transformation`(`IDTRANSFORMATION`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;

START TRANSACTION;
ALTER TABLE `heritagebytransformation` 
    ADD CONSTRAINT `FK_HERITAGEBYTRANSFORMATIONDEP_TRANSFORMATIONARR`
    FOREIGN KEY (`IDTRANSFORMATIONARR`) 
    REFERENCES `transformation`(`IDTRANSFORMATION`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;


START TRANSACTION;
ALTER TABLE `heritagebytransformation` 
    ADD CONSTRAINT `FK_HERITAGEBYTRANSFORMATION_ANALYSE` 
    FOREIGN KEY (`IDMODELANALYSIS`) 
    REFERENCES `modelanalysis`(`IDMODELANALYSIS`)
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;


SET foreign_key_checks = 1;