START TRANSACTION;
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `SAMPLES`;
CREATE TABLE IF NOT EXISTS `SAMPLES` (
    `IDSAMPLES`     bigint(20)              NULL,
    `IDCASEFILE`    bigint(20)              NULL,
    `IDBATCH`       bigint(20)              NULL,
    `IDARTICLE`     varchar(50)             NULL,
    `IDSAMPLESTYPE` bigint(20)              NULL,
    `BATCHNAME`     varchar(50)             NULL,
    `DESCRIPTION`   varchar(50) NULL,
    `CREATIONDATE`  datetime NULL,

    `IDSTATUS` smallint(6) NULL,
    `APPORVED` smallint(6) NULL,
    `APPORVEDBY` varchar(50) NULL,
    `APPORVEDDATE` datetime NULL,

PRIMARY KEY (`IDSAMPLES`),
KEY `IDSAMPLESTYPE`  (`IDSAMPLESTYPE` ),
KEY `KEY_SAMPLES_IDCASEFILE` (`IDCASEFILE`),
KEY `IDBATCH` (`IDBATCH`),
KEY `BATCHNAME` (`BATCHNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;



START TRANSACTION;
ALTER TABLE `SAMPLES` 
ADD CONSTRAINT `FK_SAMPLES_IDCASEFILE` 
FOREIGN KEY (`IDCASEFILE`) 
    REFERENCES `CASEFILE`(`IDCASEFILE`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;


START TRANSACTION;


ALTER TABLE `samples` 
ADD CONSTRAINT `FK_IDSAMPLES_IDBATCH` 
FOREIGN KEY (`IDBATCH`) 
    REFERENCES `batch`(`IDBATCH`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;


START TRANSACTION;
    ALTER TABLE `SAMPLES`
        ADD CONSTRAINT `FK_IDSAMPLES_ARTICLE` 
            FOREIGN KEY             (`IDARTICLE`) 
            REFERENCES `article`    (`IDARTICLE`);
COMMIT;

SET foreign_key_checks = 1;