

START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `MODELANALYSIS`;
CREATE TABLE IF NOT EXISTS `MODELANALYSIS` (
  `IDMODELANALYSIS` bigint(20) NULL AUTO_INCREMENT,
  `IDMOTHERANALYSIS` bigint(20) NULL ,
  `IDLIMS` varchar(50) NULL,
  `LIMSIDANALYSIS` bigint(20) NULL,
  `CATEGORY` varchar(50) NULL,
  `DESCRIPTION` varchar(50) NULL,
  `ANALYSISNAME` varchar(50) NULL,
`REPORTNAME` varchar(50) NULL,
  `OFFICIALNAME` varchar(50) NULL,
  `GROUPMEASURES` varchar(50) NULL,
 `GROUPALANALYSIS` varchar(50) NULL,
  `OFFICIALANALYSIS` tinyint(1) NULL,
  `INTERNALANALYSIS` tinyint(1) NULL,
`CANBEHERITED` tinyint(1) NULL,
PRIMARY KEY (`IDMODELANALYSIS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;
SET foreign_key_checks = 1;
