START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article` (
  `IDARTICLE` varchar(50) NULL,
  `IDSTAGE` varchar(50) NULL,
  `IDSPECIE` varchar(50) NULL,
  `IDVARIETY` varchar(50) NULL,
  IDGENERATION varchar(50) NULL,
  PRIMARY KEY (IDARTICLE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS `specie`;
CREATE TABLE IF NOT EXISTS `specie` (
  `IDSPECIE` varchar(50) NULL,
  PRIMARY KEY ( IDSPECIE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `variety`;
CREATE TABLE IF NOT EXISTS variety (IDVARIETY VARCHAR(50) NULL , IDSPECIE VARCHAR(50) NULL , PRIMARY KEY (IDVARIETY, IDSPECIE)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `generation`;
CREATE TABLE IF NOT EXISTS generation (IDGENERATION VARCHAR(50) NULL , DESCRIPTION VARCHAR(50) NULL, PRIMARY KEY (IDGENERATION));

DROP TABLE IF EXISTS `stage`;
CREATE TABLE IF NOT EXISTS stage (IDSTAGE VARCHAR(50) NULL , PRIMARY KEY (IDSTAGE));


COMMIT;

START TRANSACTION;
ALTER TABLE article ADD CONSTRAINT FK_article_IDVARIETY FOREIGN KEY (IDVARIETY) REFERENCES variety (IDVARIETY);
COMMIT;
START TRANSACTION;
ALTER TABLE article ADD CONSTRAINT FK_article_IDSTAGE FOREIGN KEY (IDSTAGE) REFERENCES STAGE (IDSTAGE);
COMMIT;
START TRANSACTION;
ALTER TABLE article ADD CONSTRAINT FK_article_IDSPECIE FOREIGN KEY (IDSPECIE) REFERENCES specie (IDSPECIE);
COMMIT;

START TRANSACTION;
ALTER TABLE article ADD CONSTRAINT FK_article_IDGENERATION FOREIGN KEY (IDGENERATION) REFERENCES generation (IDGENERATION);
COMMIT;

