

START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `TRANSFORMATION`;
CREATE TABLE IF NOT EXISTS `transformation` (
  `IDTRANSFORMATION` bigint(20) NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(50) NULL,
  `TRANSFORMATIONLABEL` int(11) NULL,
PRIMARY KEY (`IDTRANSFORMATION`) COMMENT 'PK_TRANSFORMATION'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
