START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `MEASURES`;
CREATE TABLE IF NOT EXISTS `MEASURES` (
  `IDMEASURE` bigint(20) NULL AUTO_INCREMENT,
  `MEASURENAME` varchar(50) NULL,
  `DESCRIPTION` varchar(50) NULL,
  `OFFICIALNAME` varchar(50) NULL,
  `PRINTNAME` varchar(50) NULL,
  `IDPOSSIBLEVALUE` bigint(20) NULL,
  PRIMARY KEY (`IDMEASURE`),
  KEY `IDPOSSIBLEVALUE` (`IDPOSSIBLEVALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

COMMIT;

START TRANSACTION;

ALTER TABLE `MEASURES` 
ADD CONSTRAINT `FK_IDPOSSIBLEVALUEMEASURES` 
FOREIGN KEY (`IDPOSSIBLEVALUE`) REFERENCES `possiblevaluesdetails` (`IDPOSSIBLEVALUE`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;


SET foreign_key_checks = 1;