
DROP TABLE IF EXISTS `SPECIFICATION`;
CREATE TABLE IF NOT EXISTS `SPECIFICATION` (
  `IDSPECIFICATION` bigint(20) NULL AUTO_INCREMENT,
  `IDMODELANALYSIS` bigint(20) NULL,
  `DESCRIPTION` varchar(50) NULL,
PRIMARY KEY (`IDSPECIFICATION`),
KEY `IDMODELANALYSIS` (`IDMODELANALYSIS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;