START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `treatement` ;
CREATE TABLE IF NOT EXISTS `treatement` (
  `IDTREATEMENT`    varchar(50) NULL ,
  `TREATEMENTNAME`  varchar(50) NULL,
  `DESCRIPTION`     varchar(50) NULL,
PRIMARY KEY (`IDTREATEMENT`) COMMENT 'IDTREATEMENT'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='DESCRIPTION';
COMMIT;

START TRANSACTION;

COMMIT;
SET foreign_key_checks = 1;
