START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `METHOD`;
CREATE TABLE IF NOT EXISTS `METHOD` (
  `IDMOTHER` bigint(20) NULL,
  `IDMETHOD` bigint(20) NULL,
  `METHODNAME` varchar(50) NULL,
  `DESCRIPTION` varchar(50) NULL,
  `OFFICIALNAME` varchar(50) NULL,
  `IDMODELANALYSIS` bigint(20) NULL,
  `ISVIRTUAL` tinyint(1) NULL,
  `OFFICIALANALYSIS` tinyint(1) NULL,
  `INTERNALANALYSIS` tinyint(1) NULL,
  PRIMARY KEY (`IDMETHOD`),
  KEY `IDMOTHER` (`IDMOTHER`),
  KEY `IDMODELANALYSIS` (`IDMODELANALYSIS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;

START TRANSACTION;
ALTER TABLE `method` ADD CONSTRAINT `FK_IDMODELANALYSIS` FOREIGN KEY (`IDMODELANALYSIS`) REFERENCES `modelanalysis`(`IDMODELANALYSIS`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;

START TRANSACTION;
ALTER TABLE `method` ADD CONSTRAINT `FK_IDMOTHER` FOREIGN KEY (`IDMOTHER`) REFERENCES `method`(`IDMETHOD`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;
SET foreign_key_checks = 1;