
START TRANSACTION;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `generation`;
CREATE TABLE IF NOT EXISTS generation (
    IDGENERATION    VARCHAR(50) NULL ,
    DESCRIPTION     VARCHAR(50) NULL,
    GENERATIONAME    VARCHAR(50) NULL ,
PRIMARY KEY (IDGENERATION)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;
SET foreign_key_checks = 1;