START TRANSACTION;
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `user` (
  `IDUSER` bigint(20) NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) NULL,
  `IDUSERLIMS` varchar(50) NULL,
  `SHORTNAME` varchar(50) NULL
,PRIMARY KEY (`IDUSER`) COMMENT 'PK_USER';
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

COMMIT;

START TRANSACTION;

COMMIT;
