
/*

SELECT `CONSTRAINT_CATALOG`, `CONSTRAINT_SCHEMA`, `CONSTRAINT_NAME`, `TABLE_CATALOG`, `TABLE_SCHEMA`, `TABLE_NAME`, `COLUMN_NAME`, `ORDINAL_POSITION`, `POSITION_IN_UNIQUE_CONSTRAINT`, `REFERENCED_TABLE_SCHEMA`, `REFERENCED_TABLE_NAME`, `REFERENCED_COLUMN_NAME` FROM `KEY_COLUMN_USAGE` 
where CONSTRAINT_SCHEMA='ticket' 
and ( REFERENCED_TABLE_NAME = 'RESULTS' or TABLE_NAME='RESULTS') 
or CONSTRAINT_NAME ='FK_RESULTS_IDMEASURE' 
CONSTRAINT_NAME ='FK_SAMPLES_ARTICLE'




SELECT `CONSTRAINT_CATALOG`, `CONSTRAINT_SCHEMA`, `CONSTRAINT_NAME`, `TABLE_CATALOG`, `TABLE_SCHEMA`, `TABLE_NAME`, `COLUMN_NAME`, `ORDINAL_POSITION`, `POSITION_IN_UNIQUE_CONSTRAINT`, `REFERENCED_TABLE_SCHEMA`, `REFERENCED_TABLE_NAME`, `REFERENCED_COLUMN_NAME` FROM `KEY_COLUMN_USAGE` 
where CONSTRAINT_SCHEMA='ticket' 
--and ( REFERENCED_TABLE_NAME = 'RESULTS' or TABLE_NAME='RESULTS') 
--or CONSTRAINT_NAME ='FK_RESULTS_IDMEASURE' 
and CONSTRAINT_NAME ='FK_SAMPLES_ARTICLE'


SELECT * FROM `table_constraints` WHERE `CONSTRAINT_TYPE`='PRIMARY KEY' 
*/


